### ISSUE TITLE
why i  set the “post-preview-words” it don't work，always show the whole post

### ISSUE THREAD

**Issue by elicec0** [PanosSakkos/personal-jekyll-theme#31] opened 2015-10-23 13:27 UTC
why i  set the “post-preview-words” it don't work，always show the whole post

**Comment by PanosSakkos** [comment] 2015-10-23 14:51
Hi,

The post preview's size is defined in _config.yml by the variable

````
post-preview-words: 96
````

If your post is less thatn 96 words, then yes it's expected to render whole.
But you can always reduce the post-preview-words value.

**Comment by PanosSakkos** [comment] 2015-10-23 18:58
Also not that if you are serving the website locally (not i.e on GitHub Pages), then eachtime you modify the _config.yml you have to kill (Ctr + C) the serving and start it again.

I'm closing this issue and in case that I have misunderstood your case feel free to open it again and elaborate or give a repro :smile:

**Comment by elicec0** [comment] 2015-10-31 03:27
my sample website elicec0.github.io。

**Comment by PanosSakkos** [comment] 2015-10-31 15:55
Thanks, I will have a look soon in order to see if it's a repro or not :)

**Comment by PanosSakkos** [comment] 2015-11-01 00:53
I can't reproduce it on the head of the personal-jekyll-theme repository. I have two suspicions, either you forked the repository during a regression, or liquid is acting weird with Chinese characters. 

But, I believe that the first is more probable :smile: 
So, my suggestion is to run follow [this](https://github.com/PanosSakkos/personal-jekyll-theme/wiki/How-to-integrate-latest-bug-fixes-and-features-into-your-past-fork) guide in order to integrate the latest bug fixes of personal-jekyll-theme into your repository.

**Closed by PanosSakkos** 2015-11-01 00:53 UTC

**Comment by elicec0** [comment] 2015-11-02 00:40
i will try ，thank you very much~~~
